name: Continuous Integration

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        name: Test
        steps:
            - uses: actions/checkout@v3

            - uses: actions/cache@v3
              with:
                path: |
                    ~/.cargo/registry/index/
                    ~/.cargo/git/db/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: cargo check
              run: cargo check

            - name: cargo test
              run: cargo test
    # uncomment to enable clippy lints
    # clippy:
    #     runs-on: ubuntu-latest
    #     name: Lint (clippy)
    #     steps:
    #         - uses: actions/checkout@v3
    #         - name: cargo clippy
    #           run: cargo clippy -- -D warnings

    #         - uses: actions/cache@v3
    #           with:
    #             path: |
    #                 ~/.cargo/bin/
    #                 ~/.cargo/registry/index/
    #                 ~/.cargo/registry/cache/
    #                 ~/.cargo/git/db/
    #                 target/
    #             key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
